name: Node.js CI and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]  # Run the workflow on pushes to the master branch
  pull_request:
    branches: [ "master" ]  # Run on pull requests targeting master
  workflow_dispatch:         # Allow manual triggering of the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build 

    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs successfully before deployment
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x  # Use a specific version for deployment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - run: npm ci
    - run: npm run build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Replace with your actual build directory
